### ISSUE TITLE
Invalid login attempt

### ISSUE THREAD

**Issue by Nicolaspenteado** [P-DennyGamingYT/Synapse-Beta#2]
![unknown-2](https://user-images.githubusercontent.com/100626943/203858481-92a472cc-7e15-4d4d-bb14-a7f56a88660e.png)

**Comment by Nicolaspenteado** [comment]
fix this issue.

**Comment by P-DennyGamingYT** [comment]
omg I swear I might just remove the repo. READ THE ANNOUNCEMENTS. I have said it hundreds of times. I CANT FIX IT. I'm sorry if I get upset but please top asking.
