### ISSUE TITLE
Bootstrapper Outdated

### ISSUE THREAD

**Issue by Nicolaspenteado** [P-DennyGamingYT/Synapse-Beta#3]
![imageA](https://user-images.githubusercontent.com/100626943/205522950-9e4ec474-22fe-48a0-a963-685a2df87268.png)

**Comment by P-DennyGamingYT** [comment]
Thanks for letting me know! If you can, please just DM me about the situation on Discord next time as I respond quicker and it helps me communicate faster. However, I am aware of the situation and I will look into getting an updated version. Thanks, Payson.

**Comment by mritsmemario** [comment]
same error for me

**Comment by P-DennyGamingYT** [comment]
yeah, I need to get a new version so ima work on a fix soon. Sorry guys! Ill release an announcement on the discord once I fix it.
